// Port of the effective ESLint rules, including strict type-aware checks.
import { defineConfig } from 'oxlint';

export default defineConfig({
    categories: {
        correctness: 'off',
    },
    plugins: ['typescript'],
    jsPlugins: [
        {
            name: 'toiljs',
            specifier: './presets/no-uint8array-tostring.js',
        },
    ],
    options: {
        typeAware: true,
    },
    ignorePatterns: [
        'build/**',
        'dist/**',
        'node_modules/**',
        'server/**',
        'std/server/**',
        'toil-env.d.ts',
        '.toil/**',
        'src/compiler/toil-docs.generated.ts',
    ],
    rules: {
        'eslint/constructor-super': 'off',
        'eslint/for-direction': 'error',
        'eslint/getter-return': 'off',
        'eslint/no-async-promise-executor': 'off',
        'eslint/no-case-declarations': 'error',
        'eslint/no-class-assign': 'off',
        'eslint/no-compare-neg-zero': 'error',
        'eslint/no-cond-assign': 'error',
        'eslint/no-const-assign': 'off',
        'eslint/no-constant-binary-expression': 'error',
        'eslint/no-constant-condition': 'error',
        'eslint/no-control-regex': 'error',
        'eslint/no-debugger': 'error',
        'eslint/no-delete-var': 'error',
        'eslint/no-dupe-class-members': 'off',
        'eslint/no-dupe-else-if': 'error',
        'eslint/no-dupe-keys': 'off',
        'eslint/no-duplicate-case': 'error',
        'eslint/no-empty': 'off',
        'eslint/no-empty-character-class': 'error',
        'eslint/no-empty-pattern': 'error',
        'eslint/no-empty-static-block': 'error',
        'eslint/no-ex-assign': 'error',
        'eslint/no-extra-boolean-cast': 'error',
        'eslint/no-fallthrough': 'error',
        'eslint/no-func-assign': 'off',
        'eslint/no-global-assign': 'error',
        'eslint/no-import-assign': 'off',
        'eslint/no-invalid-regexp': 'error',
        'eslint/no-irregular-whitespace': 'error',
        'eslint/no-loss-of-precision': 'error',
        'eslint/no-misleading-character-class': 'error',
        'eslint/no-new-native-nonconstructor': 'off',
        'eslint/no-nonoctal-decimal-escape': 'error',
        'eslint/no-obj-calls': 'off',
        'toiljs/no-octal': 'error',
        'eslint/no-prototype-builtins': 'error',
        'eslint/no-redeclare': 'off',
        'eslint/no-regex-spaces': 'error',
        'eslint/no-self-assign': 'error',
        'eslint/no-setter-return': 'off',
        'eslint/no-shadow-restricted-names': 'error',
        'eslint/no-sparse-arrays': 'error',
        'eslint/no-this-before-super': 'off',
        'eslint/no-unassigned-vars': 'error',
        'eslint/no-undef': 'off',
        'eslint/no-unexpected-multiline': 'error',
        'eslint/no-unreachable': 'off',
        'eslint/no-unsafe-finally': 'error',
        'eslint/no-unsafe-negation': 'off',
        'eslint/no-unsafe-optional-chaining': 'error',
        'eslint/no-unused-labels': 'error',
        'eslint/no-unused-private-class-members': 'error',
        'eslint/no-unused-vars': 'off',
        'eslint/no-useless-assignment': 'off',
        'eslint/no-useless-backreference': 'error',
        'eslint/no-useless-catch': 'error',
        'eslint/no-useless-escape': 'error',
        'eslint/no-with': 'off',
        'eslint/preserve-caught-error': 'error',
        'eslint/require-yield': 'error',
        'eslint/use-isnan': 'error',
        'eslint/valid-typeof': 'error',
        'eslint/no-var': 'error',
        'eslint/prefer-const': 'error',
        'eslint/prefer-rest-params': 'error',
        'eslint/prefer-spread': 'off',
        'typescript/await-thenable': 'error',
        'typescript/ban-ts-comment': [
            'error',
            {
                minimumDescriptionLength: 10,
            },
        ],
        'eslint/no-array-constructor': 'error',
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'off',
        'typescript/no-confusing-void-expression': 'off',
        'typescript/no-deprecated': 'error',
        'typescript/no-duplicate-enum-values': 'off',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-dynamic-delete': 'off',
        'typescript/no-empty-object-type': 'off',
        'typescript/no-explicit-any': 'error',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-extraneous-class': 'off',
        'typescript/no-floating-promises': 'error',
        'typescript/no-for-in-array': 'error',
        'eslint/no-implied-eval': 'off',
        'typescript/no-implied-eval': 'error',
        'typescript/no-invalid-void-type': 'error',
        'typescript/no-meaningless-void-operator': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-misused-promises': 'off',
        'typescript/no-misused-spread': 'error',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-nullish-coalescing': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-non-null-assertion': 'error',
        'typescript/no-redundant-type-constituents': 'off',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-unnecessary-condition': 'off',
        'typescript/no-unnecessary-template-expression': 'error',
        'typescript/no-unnecessary-type-arguments': 'off',
        'typescript/no-unnecessary-type-assertion': 'off',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unnecessary-type-conversion': 'error',
        'typescript/no-unnecessary-type-parameters': 'off',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'eslint/no-unused-expressions': 'error',
        'eslint/no-useless-constructor': 'error',
        'typescript/no-useless-default-assignment': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'eslint/no-throw-literal': 'off',
        'typescript/only-throw-error': 'off',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-literal-enum-member': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'eslint/prefer-promise-reject-errors': 'off',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/prefer-reduce-type-parameter': 'error',
        'typescript/prefer-return-this-type': 'error',
        'typescript/related-getter-setter-pairs': 'error',
        'eslint/require-await': 'off',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': [
            'error',
            {
                allowAny: false,
                allowBoolean: false,
                allowNullish: false,
                allowNumberAndString: false,
                allowRegExp: false,
            },
        ],
        'typescript/restrict-template-expressions': 'off',
        'typescript/return-await': ['error', 'error-handling-correctness-only'],
        'typescript/triple-slash-reference': 'error',
        'typescript/unbound-method': 'warn',
        'typescript/unified-signatures': 'error',
        'typescript/use-unknown-in-catch-callback-variable': 'error',
    },
});
