import { useState } from 'react';

import type { StreamChannel } from 'toiljs/client';

export const metadata: Toil.Metadata = {
    title: 'Typed @stream',
    description: 'The generated Server.Stream.Echo client: a resident per-connection @stream box.'
};

// The typed @stream client (Server.Stream.Echo, generated into shared/server.ts from the @stream catalog)
// opens a resident box. In `npm run dev` it speaks the same-origin dev WebSocket; on the Toil edge it is a
// real WebTransport session. The box (server/streams/Echo.ts) replies `pong #N` - the counter proves the
// SAME box handled every message (residency).
export default function StreamDemo() {
    const [log, setLog] = useState<string[]>([]);
    const [msg, setMsg] = useState('hello from Server.Stream');
    const [channel, setChannel] = useState<StreamChannel | null>(null);
    const add = (line: string): void => setLog((l) => [...l, line]);

    async function connect(): Promise<void> {
        // shared/server.ts (generated by the server build) attaches globalThis.Server. Import it lazily,
        // browser-only, so SSR never touches its globalThis.location access.
        await import('../../../shared/server');
        add('connecting -> /echo');
        try {
            const c = await Server.Stream.Echo.connect();
            add('session READY');
            c.onMessage((bytes) => add('<- ' + new TextDecoder().decode(bytes)));
            c.onClose((code) => add('closed (0x' + code.toString(16) + ')'));
            setChannel(c);
        } catch (e) {
            add('connect failed: ' + String(e));
        }
    }

    function send(): void {
        if (channel === null) return;
        channel.send(new TextEncoder().encode(msg));
        add('-> ' + msg);
    }

    return (
        <main>
            <h1>Typed @stream</h1>
            <p>
                <code>Server.Stream.Echo.connect()</code> opens a resident <code>@stream</code> box. In{' '}
                <code>npm run dev</code> it is the same-origin dev WebSocket; on the edge it is a real WebTransport
                session. The box replies <code>pong #N</code> - the counter proves its state survives every message.
            </p>
            <p>
                <input
                    value={msg}
                    onChange={(e) => setMsg(e.target.value)}
                    style={{ font: 'inherit', padding: '4px 8px', minWidth: 260 }}
                />
            </p>
            <p>
                <button type="button" onClick={() => void connect()} disabled={channel !== null}>
                    Connect
                </button>{' '}
                <button type="button" onClick={send} disabled={channel === null}>
                    Send
                </button>
            </p>
            <pre
                style={{
                    background: '#111',
                    color: '#ddd',
                    padding: 10,
                    borderRadius: 6,
                    minHeight: 90,
                    whiteSpace: 'pre-wrap'
                }}>
                {log.join('\n')}
            </pre>
            <p>
                <Toil.Link href="/features">Back to features</Toil.Link>
            </p>
        </main>
    );
}
