/**
 * The values the guest `render` returns for one request: the hole values the
 * edge splices into the precompiled template. The guest never emits the static
 * template bytes (the host has those, mmap'd); it only fills the holes.
 *
 * Authoring is normally generated by the toiljs compiler from the route's JSX,
 * but the typed API here is hand-writable too (it is the escape hatch). A
 * generated render looks like:
 *
 * ```ts
 * export function renderProfile(req: Request): SlotValues {
 *   const v = new SlotValues(HASH);
 *   v.setText(Slot.username, params(req, 'name'));
 *   v.setRaw(Slot.bio, bioHtml);
 *   const rows = new HtmlBuilder();
 *   for (let i = 0; i < posts.length; i++) rows.raw('<li>').text(posts[i]).raw('</li>');
 *   v.setRepeat(Slot.posts, rows);
 *   return v;
 * }
 * ```
 */

import { Header } from '../request';
import { escapeHtml } from './escape';

/** Slot kind discriminants. Mirror `toil-backend` `SlotKind` and the on-disk
 * `.slots` manifest; do not reorder. */
export namespace SlotKind {
    // @ts-ignore: decorator
    @inline export const TEXT: u8 = 0;
    // @ts-ignore: decorator
    @inline export const RAW: u8 = 1;
    // @ts-ignore: decorator
    @inline export const ATTR: u8 = 2;
    // @ts-ignore: decorator
    @inline export const REPEAT: u8 = 3;
}

/** Number of bytes in the coherence hash; must match the host's `HASH_LEN`. */
// @ts-ignore: decorator
@inline export const HASH_LEN: i32 = 32;

/** One filled hole: its stable id, kind, and the already-escaped bytes. The id
 * is held as `i32` so a generated `Slot` enum member (AS enums are `i32`) is
 * passed without a cast; it is narrowed to `u16` only at encode time. */
export class SlotValue {
    constructor(
        public slotId: i32,
        public kind: u8,
        public bytes: Uint8Array,
    ) {}
}

@inline function utf8(s: string): Uint8Array {
    return Uint8Array.wrap(String.UTF8.encode(s));
}

/**
 * Append-only HTML byte builder for repeat regions (and any place the
 * generated code assembles a run of static chunks + escaped values). `raw`
 * appends verbatim template bytes; `text`/`attr` append React-escaped values.
 * Chaining keeps generated loops terse.
 */
export class HtmlBuilder {
    private parts: Array<string> = new Array<string>();

    raw(s: string): HtmlBuilder {
        this.parts.push(s);
        return this;
    }

    text(s: string): HtmlBuilder {
        this.parts.push(escapeHtml(s));
        return this;
    }

    /** Attribute escaping is identical to text escaping in React. */
    attr(s: string): HtmlBuilder {
        this.parts.push(escapeHtml(s));
        return this;
    }

    toBytes(): Uint8Array {
        return utf8(this.parts.join(''));
    }
}

/**
 * The render result: status, coherence hash, response headers, and the ordered
 * filled holes. Serialised by `encodeValues` into the values envelope the host
 * splices against the template manifest.
 */
export class SlotValues {
    status: u16 = 200;
    headers: Array<Header> = new Array<Header>();
    slots: Array<SlotValue> = new Array<SlotValue>();

    /** `hash` is the route's compiled-in coherence hash (32 bytes); the host
     * rejects the response if it does not match the deployed template. */
    constructor(public templateHash: StaticArray<u8>) {}

    /** A text hole: React-escaped. */
    setText(slotId: i32, value: string): SlotValues {
        this.slots.push(new SlotValue(slotId, SlotKind.TEXT, utf8(escapeHtml(value))));
        return this;
    }

    /** A raw-HTML hole: inserted verbatim. The author owns sanitisation, same
     * as React `dangerouslySetInnerHTML`. */
    setRaw(slotId: i32, html: string): SlotValues {
        this.slots.push(new SlotValue(slotId, SlotKind.RAW, utf8(html)));
        return this;
    }

    /** An attribute-value hole. */
    setAttr(slotId: i32, value: string): SlotValues {
        this.slots.push(new SlotValue(slotId, SlotKind.ATTR, utf8(escapeHtml(value))));
        return this;
    }

    /** A repeat region: the guest pre-stamped + concatenated rows (built via
     * [`HtmlBuilder`]); the host inserts them verbatim at the region offset. */
    setRepeat(slotId: i32, rows: HtmlBuilder): SlotValues {
        this.slots.push(new SlotValue(slotId, SlotKind.REPEAT, rows.toBytes()));
        return this;
    }

    /** Add a response header (e.g. a Set-Cookie or Cache-Control). */
    setHeader(name: string, value: string): SlotValues {
        this.headers.push(new Header(name, value));
        return this;
    }

    setStatus(status: u16): SlotValues {
        this.status = status;
        return this;
    }
}

/** A zeroed 32-byte hash. Used for the fail-safe empty result, which the host
 * rejects as a hash mismatch (-> 500) rather than serving a broken page. */
export function zeroHash(): StaticArray<u8> {
    return new StaticArray<u8>(HASH_LEN);
}
