// AUTO-GENERATED by toil (edge SSR). Do not edit.
// Route: greeting. Slot ids match the deployed .slots manifest; HASH is the
// coherence hash the host checks against the template (deploy-skew guard).
//
// (For this example the values are hand-fixed; in a real build `template.ts`
// computes them from the route's rendered template.)

/** Stable hole ids for this route's template. */
export enum Slot {
    greeting = 0,
    count = 1,
}

/** Coherence hash (32 bytes) baked into the guest and echoed in every values
 * envelope; the host rejects a response whose hash != the deployed template. */
export const HASH: StaticArray<u8> = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
];
