/**
 * AI-assistant helper files. `toiljs create` writes a small pointer file for each tool at the
 * project root (committed, yours to edit); the real documentation lives under `.toil/docs/`,
 * regenerated on every `toiljs dev` / `toiljs build` so it stays in sync with the installed
 * toiljs version. The pointer files just tell the agent to read `.toil/docs/`.
 */
import fs from 'node:fs';
import path from 'node:path';

/** Shared body for the per-tool pointer files. */
const POINTER_BODY = `# toiljs · AI assistant guide

This is a **toiljs** project — a full-stack React framework (React + Vite client, file-based
routing, and a toilscript→WebAssembly server).

**Before editing this project, read the generated documentation in \`.toil/docs/\`.** It describes
the conventions you must follow:

- \`.toil/docs/index.md\` — overview and project layout
- \`.toil/docs/routing.md\` — file-based routing, nested layouts, loading / error files
- \`.toil/docs/client.md\` — the \`Toil\` global, Link / NavLink, router hooks
- \`.toil/docs/styling.md\` — CSS / Sass / Less / Stylus / Tailwind (via \`toiljs configure\`)
- \`.toil/docs/server.md\` — the toilscript server target
- \`.toil/docs/cli.md\` — toiljs CLI commands

\`.toil/docs/\` is regenerated by toiljs; do not edit it by hand. This pointer file is yours to edit.
`;

/** A selectable AI coding-tool helper: its id, label, and the root pointer file(s) it scaffolds. */
export interface AiHelper {
    readonly id: string;
    readonly label: string;
    readonly files: Record<string, string>;
}

/**
 * Per-tool pointer files, individually selectable in `toiljs create`. Each tool reads its own
 * conventional file: Claude Code → CLAUDE.md, Codex / others → AGENTS.md, Cursor → .cursor/rules,
 * GitHub Copilot → .github/copilot-instructions.md. Written once by `create`; not regenerated.
 */
export const AI_HELPERS: readonly AiHelper[] = [
    { id: 'claude', label: 'Claude Code (CLAUDE.md)', files: { 'CLAUDE.md': POINTER_BODY } },
    { id: 'codex', label: 'Codex / AGENTS.md', files: { 'AGENTS.md': POINTER_BODY } },
    {
        id: 'cursor',
        label: 'Cursor (.cursor/rules)',
        files: {
            '.cursor/rules/toiljs.mdc': `---\ndescription: toiljs project conventions\nalwaysApply: true\n---\n\n${POINTER_BODY}`,
        },
    },
    {
        id: 'copilot',
        label: 'GitHub Copilot (.github/copilot-instructions.md)',
        files: { '.github/copilot-instructions.md': POINTER_BODY },
    },
];

/** All AI helper ids (the default selection). */
export const AI_HELPER_IDS: readonly string[] = AI_HELPERS.map((h) => h.id);

/** Merges the pointer files for the given helper ids into one path → content map. */
export function aiHelperFiles(ids: readonly string[]): Record<string, string> {
    const out: Record<string, string> = {};
    for (const helper of AI_HELPERS) {
        if (ids.includes(helper.id)) Object.assign(out, helper.files);
    }
    return out;
}

/** The framework docs written into `.toil/docs/` (placeholders for now), keyed by filename. */
export const TOIL_DOCS: Record<string, string> = {
    'index.md': '# toiljs\n\n<!-- TODO: overview and project layout -->\n',
    'routing.md': '# Routing\n\n<!-- TODO: file-based routing, nested layouts, loading / error -->\n',
    'client.md': '# Client runtime\n\n<!-- TODO: Toil global, Link / NavLink, router hooks -->\n',
    'styling.md': '# Styling\n\n<!-- TODO: CSS / preprocessors / Tailwind via `toiljs configure` -->\n',
    'server.md': '# Server (toilscript → WebAssembly)\n\n<!-- TODO -->\n',
    'cli.md': '# CLI\n\n<!-- TODO: create / dev / build / start / configure -->\n',
};

/** Writes the framework docs into `<toilDir>/docs/`. Called by `generate` each dev/build. */
export function writeDocs(toilDir: string): void {
    const dir = path.join(toilDir, 'docs');
    fs.mkdirSync(dir, { recursive: true });
    for (const [name, content] of Object.entries(TOIL_DOCS)) {
        fs.writeFileSync(path.join(dir, name), content);
    }
}
