import fs from 'node:fs';
import path from 'node:path';

import { type ResolvedToilConfig } from './config.js';
import { scanRoutes, type ScannedRoute } from './routes.js';

/** Returns a `./`-prefixed POSIX path from the `.toil` dir to `abs`, for use in generated imports. */
function relFromToil(cfg: ResolvedToilConfig, abs: string): string {
    let rel = path.relative(cfg.toilDir, abs).replace(/\\/g, '/');
    if (!rel.startsWith('.')) rel = './' + rel;
    return rel;
}

function findLayout(cfg: ResolvedToilConfig): string | undefined {
    return ['layout.tsx', 'layout.jsx']
        .map((name) => path.join(cfg.clientAbsDir, name))
        .find((p) => fs.existsSync(p));
}

/** Finds an optional custom not-found page at `client/404.{tsx,jsx}`. */
function findNotFound(cfg: ResolvedToilConfig): string | undefined {
    return ['404.tsx', '404.jsx']
        .map((name) => path.join(cfg.clientAbsDir, name))
        .find((p) => fs.existsSync(p));
}

/**
 * Generates the `.toil/` working dir (routes table, mount entry, HTML) and returns the scanned
 * routes. Called before every dev/build and on route add/remove during dev.
 */
export function generate(cfg: ResolvedToilConfig): ScannedRoute[] {
    const routes = scanRoutes(cfg.routesAbsDir);
    fs.mkdirSync(cfg.toilDir, { recursive: true });

    const layoutFile = findLayout(cfg);
    const notFoundFile = findNotFound(cfg);
    const routesSrc =
        `// AUTO-GENERATED by toil — do not edit.\n` +
        `import type { RouteDef, LayoutLoader, NotFoundLoader } from 'toiljs/client';\n\n` +
        `export const routes: RouteDef[] = [\n` +
        routes
            .map(
                (r) =>
                    `  { pattern: ${JSON.stringify(r.pattern)}, load: () => import(${JSON.stringify(relFromToil(cfg, r.file))}) },`,
            )
            .join('\n') +
        `\n];\n\n` +
        `export const layout: LayoutLoader = ${layoutFile ? `() => import(${JSON.stringify(relFromToil(cfg, layoutFile))})` : 'null'};\n` +
        `export const notFound: NotFoundLoader = ${notFoundFile ? `() => import(${JSON.stringify(relFromToil(cfg, notFoundFile))})` : 'null'};\n`;
    fs.writeFileSync(path.join(cfg.toilDir, 'routes.ts'), routesSrc);

    const entrySrc =
        `// AUTO-GENERATED by toil — do not edit.\n` +
        `import { mount } from 'toiljs/client';\n` +
        `import { BinaryWriter, BinaryReader, FastMap, FastSet } from 'toiljs/io';\n` +
        `import { routes, layout, notFound } from './routes';\n\n` +
        `// Expose toiljs IO as native globals (typed via ./toil-env.d.ts).\n` +
        `Object.assign(globalThis, { BinaryWriter, BinaryReader, FastMap, FastSet });\n\n` +
        `mount(routes, layout, notFound);\n`;
    fs.writeFileSync(path.join(cfg.toilDir, 'entry.tsx'), entrySrc);

    // Ambient global types so `new BinaryWriter()` etc. resolve in the IDE without an import.
    // Script-mode declaration file (no top-level import/export → the `declare const`s are truly
    // global, and it's not a module so it can't confuse ESLint's project service). The inline
    // `import('toiljs/io')` type only needs the normal `toiljs/io` export to resolve. At the
    // project root because TypeScript's `include` globs skip dot-directories (like next-env.d.ts).
    const envSrc =
        `// AUTO-GENERATED by toil — do not edit.\n` +
        `declare const BinaryWriter: typeof import('toiljs/io').BinaryWriter;\n` +
        `declare const BinaryReader: typeof import('toiljs/io').BinaryReader;\n` +
        `declare const FastMap: typeof import('toiljs/io').FastMap;\n` +
        `declare const FastSet: typeof import('toiljs/io').FastSet;\n`;
    fs.writeFileSync(path.join(cfg.root, 'toil-env.d.ts'), envSrc);

    const htmlSrc =
        `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n` +
        `    <meta name="viewport" content="width=device-width, initial-scale=1" />\n` +
        `    <title>Toil App</title>\n  </head>\n  <body>\n    <div id="root"></div>\n` +
        `    <script type="module" src="./entry.tsx"></script>\n  </body>\n</html>\n`;
    fs.writeFileSync(path.join(cfg.toilDir, 'index.html'), htmlSrc);

    return routes;
}
