import fs from 'node:fs';
import path from 'node:path';

import { type ResolvedToilConfig } from './config.js';
import { scanRoutes, type ScannedRoute } from './routes.js';

/**
 * Contents of the root `toil-env.d.ts`: ambient global types so `new BinaryWriter()` etc. resolve
 * in the IDE without an import. Script-mode declaration (no top-level import/export → the
 * `declare const`s are truly global, and it's not a module that could confuse ESLint's project
 * service); the inline `import('toiljs/io')` type only needs the normal `toiljs/io` export.
 * Lives at the project root because TypeScript's `include` globs skip dot-directories.
 * Exported so `toiljs create` can write it during scaffolding, before the first dev/build.
 */
export const TOIL_ENV_DTS =
    `// AUTO-GENERATED by toil — do not edit.\n` +
    `declare const BinaryWriter: typeof import('toiljs/io').BinaryWriter;\n` +
    `declare const BinaryReader: typeof import('toiljs/io').BinaryReader;\n` +
    `declare const FastMap: typeof import('toiljs/io').FastMap;\n` +
    `declare const FastSet: typeof import('toiljs/io').FastSet;\n`;

/**
 * Returns a `./`-prefixed, **extensionless** POSIX module specifier from `.toil` to `abs`, for use
 * in generated `import(...)` calls. Extensionless so TypeScript doesn't demand
 * `allowImportingTsExtensions` (TS5097) when the generated files are checked; Vite still resolves it.
 */
function relFromToil(cfg: ResolvedToilConfig, abs: string): string {
    let rel = path.relative(cfg.toilDir, abs).replace(/\\/g, '/').replace(/\.(tsx|jsx)$/, '');
    if (!rel.startsWith('.')) rel = './' + rel;
    return rel;
}

function findLayout(cfg: ResolvedToilConfig): string | undefined {
    return ['layout.tsx', 'layout.jsx']
        .map((name) => path.join(cfg.clientAbsDir, name))
        .find((p) => fs.existsSync(p));
}

/** Finds an optional custom not-found page at `client/404.{tsx,jsx}`. */
function findNotFound(cfg: ResolvedToilConfig): string | undefined {
    return ['404.tsx', '404.jsx']
        .map((name) => path.join(cfg.clientAbsDir, name))
        .find((p) => fs.existsSync(p));
}

/**
 * Generates the `.toil/` working dir (routes table, mount entry, the HTML entry built from the
 * project's `public/index.html` template, and mirrored `public/` assets) and returns the scanned
 * routes. Called before every dev/build and on route add/remove during dev.
 */
export function generate(cfg: ResolvedToilConfig): ScannedRoute[] {
    const routes = scanRoutes(cfg.routesAbsDir);
    fs.mkdirSync(cfg.toilDir, { recursive: true });

    const layoutFile = findLayout(cfg);
    const notFoundFile = findNotFound(cfg);
    const routesSrc =
        `// @ts-nocheck\n` +
        `// AUTO-GENERATED by toil — do not edit.\n` +
        `import type { RouteDef, LayoutLoader, NotFoundLoader } from 'toiljs/client';\n\n` +
        `export const routes: RouteDef[] = [\n` +
        routes
            .map(
                (r) =>
                    `  { pattern: ${JSON.stringify(r.pattern)}, load: () => import(${JSON.stringify(relFromToil(cfg, r.file))}) },`,
            )
            .join('\n') +
        `\n];\n\n` +
        `export const layout: LayoutLoader = ${layoutFile ? `() => import(${JSON.stringify(relFromToil(cfg, layoutFile))})` : 'null'};\n` +
        `export const notFound: NotFoundLoader = ${notFoundFile ? `() => import(${JSON.stringify(relFromToil(cfg, notFoundFile))})` : 'null'};\n`;
    fs.writeFileSync(path.join(cfg.toilDir, 'routes.ts'), routesSrc);

    const entrySrc =
        `// @ts-nocheck\n` +
        `// AUTO-GENERATED by toil — do not edit.\n` +
        `import { mount } from 'toiljs/client';\n` +
        `import { BinaryWriter, BinaryReader, FastMap, FastSet } from 'toiljs/io';\n` +
        `import { routes, layout, notFound } from './routes';\n\n` +
        `// Expose toiljs IO as native globals (typed via ./toil-env.d.ts).\n` +
        `Object.assign(globalThis, { BinaryWriter, BinaryReader, FastMap, FastSet });\n\n` +
        `mount(routes, layout, notFound);\n`;
    fs.writeFileSync(path.join(cfg.toilDir, 'entry.tsx'), entrySrc);

    // Ambient global types (see TOIL_ENV_DTS). Regenerated each dev/build; also written by
    // `toiljs create` so a fresh project type-checks before its first build.
    fs.writeFileSync(path.join(cfg.root, 'toil-env.d.ts'), TOIL_ENV_DTS);

    fs.writeFileSync(path.join(cfg.toilDir, 'index.html'), buildHtml(cfg));
    syncPublicAssets(cfg);

    return routes;
}

/** Fallback HTML when the project has no `public/index.html` template. The entry script is added
 * by {@link buildHtml}. */
const DEFAULT_HTML =
    `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n` +
    `    <meta name="viewport" content="width=device-width, initial-scale=1" />\n` +
    `    <title>Toil App</title>\n  </head>\n  <body>\n    <div id="root"></div>\n` +
    `  </body>\n</html>\n`;

/** The module entry that boots the app, injected into the HTML (resolved relative to `.toil`). */
const ENTRY_SCRIPT = `<script type="module" src="./entry.tsx"></script>`;

/**
 * Produces the `.toil/index.html` Vite entry from the project's `public/index.html` template (or
 * the built-in default if absent), ensuring the generated module entry script is present. Users
 * own the template — toil only guarantees the entry is wired, so it stays the SPA root.
 */
function buildHtml(cfg: ResolvedToilConfig): string {
    const templatePath = path.join(cfg.publicDir, 'index.html');
    let html = fs.existsSync(templatePath)
        ? fs.readFileSync(templatePath, 'utf8')
        : DEFAULT_HTML;
    if (!html.includes('entry.tsx')) {
        html = html.includes('</body>')
            ? html.replace('</body>', `    ${ENTRY_SCRIPT}\n  </body>`)
            : `${html}\n${ENTRY_SCRIPT}\n`;
    }
    return html;
}

/**
 * Mirrors the project's `public/` assets into `.toil/public/` (Vite's publicDir under the `.toil`
 * root), excluding the `index.html` template — that is processed into the entry above, and copying
 * it here would clobber the built, asset-hashed page. Cleared each run so deletions propagate.
 */
function syncPublicAssets(cfg: ResolvedToilConfig): void {
    const dest = path.join(cfg.toilDir, 'public');
    fs.rmSync(dest, { recursive: true, force: true });
    if (!fs.existsSync(cfg.publicDir)) return;

    let copied = 0;
    for (const entry of fs.readdirSync(cfg.publicDir, { withFileTypes: true })) {
        if (entry.name === 'index.html') continue;
        fs.cpSync(path.join(cfg.publicDir, entry.name), path.join(dest, entry.name), {
            recursive: true,
        });
        copied++;
    }
    if (copied === 0) fs.rmSync(dest, { recursive: true, force: true });
}
