/**
 * Build-time codegen of the AssemblyScript surface a route's guest `render`
 * uses. From the extracted holes (see `template.ts`) this emits:
 *
 *   - a `Slot` enum (hole name -> stable numeric id, the SAME ids the host
 *     `.slots` manifest carries), so host and guest agree by construction; and
 *   - the coherence `HASH` (32 bytes) compiled into the guest and echoed in
 *     every values envelope; the host 500s on a mismatch (deploy skew).
 *
 * The render BODY is authored against `SlotValues` (the typed, hand-writable
 * API). A route's `render(req)` derives its data from the request/edge and
 * fills the slots:
 *
 * ```ts
 * import { Request } from 'toiljs/server/runtime';
 * import { SlotValues } from 'toiljs/server/runtime/ssr/slots';
 * import { Slot, HASH } from './_ssr/u_name.slots';
 *
 * export function renderUName(req: Request): SlotValues {
 *   const v = new SlotValues(HASH);
 *   v.setText(Slot.username, pathParam(req, 'name'));
 *   v.setRaw(Slot.bio, bio);
 *   const rows = new HtmlBuilder();
 *   for (let i = 0; i < posts.length; i++) rows.raw('<li>').text(posts[i]).raw('</li>');
 *   v.setRepeat(Slot.posts, rows);
 *   return v;
 * }
 * ```
 *
 * Generating that body automatically from the JSX-subset bindings is a later
 * phase; the typed enum + hash here are what make a hand-written or generated
 * body coherent with the deployed template.
 */

import type { SlotRecord } from './template.js';
import { assignSlotIds } from './template.js';

/** Emit a `StaticArray<u8>` literal of the 32 hash bytes. */
function hashLiteral(hash: Buffer): string {
    const bytes = Array.from(hash.values())
        .map((b) => `0x${b.toString(16).padStart(2, '0')}`)
        .join(', ');
    return `[${bytes}]`;
}

/** A slot name is a valid AS enum member iff it is a bare identifier; anything
 * else (e.g. a hyphenated id) is rejected so the generated module can't break
 * or smuggle code. */
function isIdent(name: string): boolean {
    return /^[A-Za-z_$][\w$]*$/.test(name);
}

/**
 * Generate the `<route>.slots.ts` AssemblyScript module: the `Slot` enum and
 * the `HASH` constant. `slots` is the top-level slot list from
 * `extractFromHtml`; ids are assigned in document order to match the host
 * `.slots` manifest written by `encodeSlots`.
 */
export function generateSlotsModule(routeName: string, slots: SlotRecord[], hash: Buffer): string {
    if (hash.length !== 32) throw new Error('toil ssr: coherence hash must be 32 bytes');
    const ids = assignSlotIds(slots);
    const members: string[] = [];
    for (const [name, id] of ids) {
        if (!isIdent(name)) {
            throw new Error(
                `toil ssr: hole id "${name}" in route "${routeName}" is not a valid identifier ` +
                    `(use [A-Za-z_][\\w]*) so it can be a Slot enum member`,
            );
        }
        members.push(`    ${name} = ${id},`);
    }
    return `// AUTO-GENERATED by toil (edge SSR). Do not edit.
// Route: ${routeName}. Slot ids match the deployed .slots manifest; HASH is the
// coherence hash the host checks against the template (deploy-skew guard).

/** Stable hole ids for this route's template. */
export enum Slot {
${members.join('\n')}
}

/** Coherence hash (32 bytes) baked into the guest and echoed in every values
 * envelope; the host rejects a response whose hash != the deployed template. */
export const HASH: StaticArray<u8> = ${hashLiteral(hash)};
`;
}
