import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import pc from 'picocolors';
import react from '@vitejs/plugin-react';
import { imagetools } from 'vite-imagetools';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import { createLogger, type InlineConfig, type Logger, mergeConfig, type PluginOption } from 'vite';

import { type ResolvedToilConfig } from './config.js';
import { fontPreloadPlugin } from './fonts.js';
import { imageReportPlugin } from './image-report.js';
import { toilPlugin } from './plugin.js';
import { prerenderPlugin } from './prerender.js';

// `vite-plugin-node-polyfills` rewrites react/react-dom to import its `vite-plugin-node-polyfills/
// shims/*` modules. When a consumer links toiljs by symlink (`file:`/workspace), that package lives
// only in toiljs's own node_modules, so resolving those bare specifiers from the consumer root
// fails ("Failed to resolve import vite-plugin-node-polyfills/shims/process"). Alias them to
// absolute paths resolved from toiljs's location so the build works however toiljs was installed.
const polyfillPkgRoot = path.dirname(
    path.dirname(createRequire(import.meta.url).resolve('vite-plugin-node-polyfills')),
);
const polyfillShimAliases: Record<string, string> = {
    'vite-plugin-node-polyfills/shims/buffer': path.join(
        polyfillPkgRoot,
        'shims/buffer/dist/index.js',
    ),
    'vite-plugin-node-polyfills/shims/global': path.join(
        polyfillPkgRoot,
        'shims/global/dist/index.js',
    ),
    'vite-plugin-node-polyfills/shims/process': path.join(
        polyfillPkgRoot,
        'shims/process/dist/index.js',
    ),
};

/** Image extensions routed to `images/` in the build output. */
const IMAGE_EXT = /^(png|jpe?g|svg|gif|tiff|bmp|ico|webp|avif)$/i;
/** Font extensions routed to `fonts/`. */
const FONT_EXT = /^(woff|woff2|eot|ttf|otf)$/i;

/**
 * Resolves bare `shared/*` imports to the project's `shared/` folder (replacing a plain alias so it
 * can run early), and fails `shared/server` with an actionable message when the module has not been
 * generated yet (it comes from the server build, which must run first), instead of Vite's opaque
 * `UNLOADABLE_DEPENDENCY`.
 */
function sharedResolverPlugin(cfg: ResolvedToilConfig): PluginOption {
    const sharedDir = path.join(cfg.root, 'shared');
    const serverModule = path.join(sharedDir, 'server.ts');
    // Posix-normalized: Vite hands `transform` forward-slash module ids while path.join is OS-native, so a
    // raw `===` would silently never match on Windows (the surface would regress to "client not loaded").
    const routesModule = path.join(cfg.toilDir, 'routes.ts').replace(/\\/g, '/');
    return {
        name: 'toiljs:shared-resolver',
        enforce: 'pre',
        resolveId(source: string) {
            if (source !== 'shared' && !source.startsWith('shared/')) return null;
            const rel = source === 'shared' ? 'index' : source.slice('shared/'.length);
            for (const ext of ['', '.ts', '.tsx', '.js', '.jsx', '.mjs']) {
                const candidate = path.join(sharedDir, rel + ext);
                if (fs.existsSync(candidate)) return candidate;
            }
            if (source === 'shared/server') {
                throw new Error(
                    'toiljs: "shared/server" is generated by the server build but is missing. ' +
                        'Run the server build first (it emits shared/server.ts from your @data/@remote code): ' +
                        '`npm run build:server`  (toilscript --target release --rpcModule shared/server.ts).',
                );
            }
            return null;
        },
        transform(code: string, id: string) {
            // Guarantee the generated client surface (shared/server.ts: __toilRest/__toilRpc/__toilStream
            // + globalThis.Server) is EVALUATED. Otherwise it is dead unless some route happens to
            // value-import a @data type - a type-only import is erased and never attaches, so
            // `Server.<rpc>()` / `Server.REST` / `Server.Stream` would throw "client not loaded". Inject a
            // side-effect import from the always-loaded route manifest; idempotent and a no-op for a
            // client-only project (no shared/server.ts).
            if ((id.split('?')[0] ?? id).replace(/\\/g, '/') === routesModule && fs.existsSync(serverModule)) {
                return { code: `import 'shared/server';\n${code}`, map: null };
            }
            return null;
        },
    };
}

/** Routes a built asset to a typed sub-folder (`images/`, `fonts/`, `css/`, else `assets/`). */
function assetFileName(name: string): string {
    const ext = name.split('.').pop() ?? '';
    if (IMAGE_EXT.test(ext)) return 'images/[name][extname]';
    if (FONT_EXT.test(ext)) return 'fonts/[name][extname]';
    if (/^css$/i.test(ext)) return 'css/[name][extname]';
    return 'assets/[name][extname]';
}

/**
 * Loads the Tailwind v4 Vite plugin if the project has `@tailwindcss/vite` installed (added by
 * `toiljs create`/`configure` when Tailwind is enabled). Resolved from the project root so it picks
 * up the project's copy; returns `undefined` when Tailwind is off, so the plugin simply isn't added.
 */
async function tailwindPlugin(root: string): Promise<PluginOption | undefined> {
    let resolved: string;
    try {
        resolved = createRequire(path.join(root, 'package.json')).resolve('@tailwindcss/vite');
    } catch {
        return undefined;
    }
    const mod = (await import(pathToFileURL(resolved).href)) as { default?: () => PluginOption };
    return mod.default?.();
}

/** Splits React's runtime into its own long-lived chunk for better caching. */
function manualChunks(id: string): string | undefined {
    if (!id.includes('node_modules')) return undefined;
    if (
        id.includes('node_modules/react-dom') ||
        id.includes('node_modules/react/') ||
        id.includes('node_modules/scheduler')
    ) {
        return 'react';
    }
    return undefined;
}

/**
 * Builds the framework-owned Vite config. Vite's `root` is the generated `.toil` dir so its
 * `index.html` (built from the project's `public/index.html` template) emits at the output root
 * with assets resolving correctly; static `public/` assets are mirrored to `.toil/public` and
 * picked up via Vite's default publicDir. `fs.allow` opens the project (for `client/`) and the
 * framework runtime. The opinionated default, Node polyfills
 * (Buffer/global/process), React plugin, toil route plugin, typed asset folders, React chunk
 * splitting and tuned build options, is applied here; `toiljs/client` is aliased to the
 * runtime, and the user's `client.vite` overrides deep-merge on top.
 */
/**
 * Vite's `(ssr)` environment label is dark blue — nearly invisible on a black
 * terminal. Wrap the default logger to recolor `(ssr)` magenta (purple) and
 * `(client)` cyan, so the dev reload logs are readable.
 */
function brandedLogger(): Logger {
    const logger = createLogger();
    const recolor = (msg: string): string =>
        msg
            .replace(/(?:\[[0-9;]*m)*\(ssr\)(?:\[[0-9;]*m)*/g, pc.magenta('(ssr)'))
            .replace(/(?:\[[0-9;]*m)*\(client\)(?:\[[0-9;]*m)*/g, pc.cyan('(client)'));
    const info = logger.info.bind(logger);
    const warn = logger.warn.bind(logger);
    logger.info = (msg, opts) => info(recolor(msg), opts);
    logger.warn = (msg, opts) => warn(recolor(msg), opts);
    return logger;
}

export async function createViteConfig(cfg: ResolvedToilConfig): Promise<InlineConfig> {
    const frameworkRoot = path.resolve(path.dirname(cfg.runtimePath), '..', '..');
    const tailwind = await tailwindPlugin(cfg.root);

    const base: InlineConfig = {
        root: cfg.toilDir,
        base: cfg.base,
        configFile: false,
        customLogger: brandedLogger(),
        plugins: [
            tailwind,
            // Build-time image resize/optimization. Every *imported* raster image is compressed to
            // webp by default (so a plain `<img src={imported}>` is optimized too, not just
            // `Toil.Image`); add `?w=400;800&format=…` to resize or pick a format. `public/` assets
            // referenced by string path are served as-is. Disabled by `client.images: false`.
            cfg.images
                ? imagetools({
                      defaultDirectives: () =>
                          new URLSearchParams({ format: 'webp', quality: '80' }),
                  })
                : undefined,
            cfg.images ? imageReportPlugin(cfg.root, cfg.toilDir) : undefined,
            // Static per-route SEO prerender (build only): bakes each route's metadata into its HTML.
            cfg.seo ? prerenderPlugin(cfg) : undefined,
            // Preload bundled fonts (build only). Disabled by `client.fonts: false`.
            cfg.fonts ? fontPreloadPlugin(cfg) : undefined,
            nodePolyfills({ globals: { Buffer: true, global: true, process: true } }),
            react(),
            sharedResolverPlugin(cfg),
            toilPlugin(cfg),
        ],
        resolve: {
            alias: {
                'toiljs/client': cfg.runtimePath,
                'toiljs/routes': path.join(cfg.toilDir, 'routes.ts'),
                // `client/*` -> the project's client source dir, so anything (pages, and notably
                // `emails/*.tsx`) can reuse existing client assets, e.g. `import 'client/styles/x.css'`.
                // Vite's string alias matches only `client` or `client/...`, never `toiljs/client`.
                client: cfg.clientAbsDir,
                // `shared/*` is resolved by sharedResolverPlugin (above) so a missing generated
                // shared/server.ts gives an actionable error instead of an opaque load failure.
                ...polyfillShimAliases,
            },
            dedupe: ['react', 'react-dom'],
        },
        server: {
            port: cfg.port,
            fs: { allow: [cfg.root, frameworkRoot] },
        },
        build: {
            outDir: path.resolve(cfg.root, cfg.outDir),
            emptyOutDir: true,
            target: 'es2020',
            modulePreload: false,
            cssCodeSplit: false,
            assetsInlineLimit: 10000,
            chunkSizeWarningLimit: 3000,
            commonjsOptions: {
                strictRequires: true,
                transformMixedEsModules: true,
            },
            rollupOptions: {
                output: {
                    chunkFileNames: 'assets/[name]-[hash].js',
                    assetFileNames: (assetInfo) => assetFileName(assetInfo.names[0] ?? ''),
                    manualChunks,
                },
            },
        },
    };
    return mergeConfig(base, cfg.vite);
}
