/**
 * The client-callable server surface (`Server`). Its TYPED shape is generated by
 * the toilscript server build into the project's `shared/server.ts`
 * (`declare global { const Server }`); this module is the runtime behind it.
 *
 * Three surfaces live under `Server`, all attached by the generated `shared/server.ts` on import:
 *   - `Server.REST.<controller>.<route>(args)` - a fetch client (`globalThis.__toilRest`).
 *   - `Server.Stream.<class>.connect()` - the stream client (`globalThis.__toilStream`).
 *   - `Server.<service>.<method>(args)` and a free `Server.<remote>(args)` - the RPC client
 *     (`globalThis.__toilRpc`): each POSTs to `/__toil_rpc` with a method id and @data-encoded args.
 * Build the server (`npm run build:server`) to (re)generate the typed surface + attach the clients.
 */

/** A recursive proxy that throws on call, used when the REST client hasn't loaded. */
function restMissingStub(path: string): unknown {
    const call = (): never => {
        throw new Error(
            `toiljs REST: ${path}() is unavailable. The generated REST client has not loaded - ` +
                `run 'npm run build:server' to generate shared/server.ts; the client then attaches automatically.`,
        );
    };
    return new Proxy(call, {
        get(_target, prop) {
            if (typeof prop === 'symbol' || prop === 'then') return undefined;
            return restMissingStub(`${path}.${prop}`);
        },
        apply() {
            return call();
        },
    });
}

/** A recursive proxy that throws on call, used when the stream client hasn't loaded. */
function streamMissingStub(path: string): unknown {
    const call = (): never => {
        throw new Error(
            `toiljs Stream: ${path}() is unavailable. The generated stream client has not loaded - ` +
                `run 'npm run build:server' to generate shared/server.ts; the client then attaches automatically.`,
        );
    };
    return new Proxy(call, {
        get(_target, prop) {
            if (typeof prop === 'symbol' || prop === 'then') return undefined;
            return streamMissingStub(`${path}.${prop}`);
        },
        apply() {
            return call();
        },
    });
}

/** Builds a recursive proxy that throws on call, supporting `Server.svc.method()`. */
function rpcStub(path: string): unknown {
    const call = (): never => {
        throw new Error(
            `toiljs RPC: ${path}() is unavailable. The generated RPC client has not loaded - ` +
                `run 'npm run build:server' to generate shared/server.ts; the client then attaches automatically.`,
        );
    };
    return new Proxy(call, {
        get(_target, prop) {
            // Not thenable, and ignore symbol probes (e.g. from awaiting/inspection).
            if (typeof prop === 'symbol' || prop === 'then') return undefined;
            // `Server.REST` surfaces the generated fetch client attached by shared/server.ts.
            if (path === 'Server' && prop === 'REST') {
                const rest = (globalThis as { __toilRest?: unknown }).__toilRest;
                return rest !== undefined ? rest : restMissingStub('Server.REST');
            }
            // `Server.Stream` surfaces the generated stream client attached by shared/server.ts.
            if (path === 'Server' && prop === 'Stream') {
                const stream = (globalThis as { __toilStream?: unknown }).__toilStream;
                return stream !== undefined ? stream : streamMissingStub('Server.Stream');
            }
            // `Server.<service>` / `Server.<remote>` surface the generated RPC client. Its top-level
            // keys are the @service names (-> a `{ method }` object) and free @remote functions.
            if (path === 'Server') {
                const rpc = (globalThis as { __toilRpc?: Record<string, unknown> }).__toilRpc;
                if (rpc !== undefined && prop in rpc) return rpc[prop];
            }
            return rpcStub(`${path}.${prop}`);
        },
        apply() {
            return call();
        },
    });
}

/**
 * Runtime value for the global `Server`. Typed as `unknown` here; the real types
 * come from the generated `shared/server.ts`. toiljs assigns this to `globalThis`.
 */
export const Server: unknown = rpcStub('Server');

// Back the generated `declare global { const Server }` (shared/server.ts) with a runtime value, so an
// app reaches `Server.REST` / `Server.Stream.<Name>` via the global without an import (the design note
// above). Idempotent - the proxy is a singleton; importing `toiljs/client` evaluates this once.
(globalThis as Record<string, unknown>).Server = Server;
