/**
 * The client-callable server surface (`Server`). Its TYPED shape is generated by
 * the toilscript server build into the project's `shared/server.ts`
 * (`declare global { const Server }`); this module is the runtime behind it.
 *
 * Two surfaces live under `Server`:
 *   - `Server.REST.<controller>.<route>(args)` is a WORKING fetch client. The
 *     generated `shared/server.ts` attaches it to `globalThis.__toilRest` when
 *     imported; the proxy below surfaces it under `Server.REST`.
 *   - `Server.<service>.<method>()` (RPC) is not wired yet, so any call throws.
 *     The pipeline (tags -> generated types -> proxy) is in place; only the
 *     network dispatch is a TODO. Build the server (`npm run build:server`) to
 *     (re)generate the typed surface.
 */

/** A recursive proxy that throws on call, used when the REST client hasn't loaded. */
function restMissingStub(path: string): unknown {
    const call = (): never => {
        throw new Error(
            `toiljs REST: ${path}() is unavailable. The generated REST client has not loaded - ` +
                `import a type from your 'shared/server' (so the client attaches), or run 'npm run build:server'.`,
        );
    };
    return new Proxy(call, {
        get(_target, prop) {
            if (typeof prop === 'symbol' || prop === 'then') return undefined;
            return restMissingStub(`${path}.${prop}`);
        },
        apply() {
            return call();
        },
    });
}

/** A recursive proxy that throws on call, used when the stream client hasn't loaded. */
function streamMissingStub(path: string): unknown {
    const call = (): never => {
        throw new Error(
            `toiljs Stream: ${path}() is unavailable. The generated stream client has not loaded - ` +
                `import a type from your 'shared/server' (so the client attaches), or run 'npm run build:server'.`,
        );
    };
    return new Proxy(call, {
        get(_target, prop) {
            if (typeof prop === 'symbol' || prop === 'then') return undefined;
            return streamMissingStub(`${path}.${prop}`);
        },
        apply() {
            return call();
        },
    });
}

/** Builds a recursive proxy that throws on call, supporting `Server.svc.method()`. */
function rpcStub(path: string): unknown {
    const call = (): never => {
        throw new Error(
            `toiljs RPC: ${path}() is not available yet. The client<->server transport ` +
                `is not wired; this is a generated stub. Remote calls will work once transport lands.`,
        );
    };
    return new Proxy(call, {
        get(_target, prop) {
            // Not thenable, and ignore symbol probes (e.g. from awaiting/inspection).
            if (typeof prop === 'symbol' || prop === 'then') return undefined;
            // `Server.REST` surfaces the generated fetch client attached by shared/server.ts.
            if (path === 'Server' && prop === 'REST') {
                const rest = (globalThis as { __toilRest?: unknown }).__toilRest;
                return rest !== undefined ? rest : restMissingStub('Server.REST');
            }
            // `Server.Stream` surfaces the generated stream client attached by shared/server.ts.
            if (path === 'Server' && prop === 'Stream') {
                const stream = (globalThis as { __toilStream?: unknown }).__toilStream;
                return stream !== undefined ? stream : streamMissingStub('Server.Stream');
            }
            return rpcStub(`${path}.${prop}`);
        },
        apply() {
            return call();
        },
    });
}

/**
 * Runtime value for the global `Server`. Typed as `unknown` here; the real types
 * come from the generated `shared/server.ts`. toiljs assigns this to `globalThis`.
 */
export const Server: unknown = rpcStub('Server');

// Back the generated `declare global { const Server }` (shared/server.ts) with a runtime value, so an
// app reaches `Server.REST` / `Server.Stream.<Name>` via the global without an import (the design note
// above). Idempotent - the proxy is a singleton; importing `toiljs/client` evaluates this once.
(globalThis as Record<string, unknown>).Server = Server;
