// AUTO-GENERATED by toil — do not edit.
import type {
    BinaryWriter as ToilBinaryWriter,
    BinaryReader as ToilBinaryReader,
    FastMap as ToilFastMap,
    FastSet as ToilFastSet,
} from 'toiljs/io';

declare global {
    const BinaryWriter: typeof ToilBinaryWriter;
    const BinaryReader: typeof ToilBinaryReader;
    const FastMap: typeof ToilFastMap;
    const FastSet: typeof ToilFastSet;
}

export {};
